version: 0.0
os: linux

files:
  - source: /
    destination: /usr/src/app

hooks:
  BeforeInstall:
    - location: hooks/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: hooks/application_start.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: hooks/validate_service.sh
      timeout: 300
      runas: ec2-user